# Generated by Django 4.1 on 2022-10-13 16:47

import apps.news.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                (
                    "image",
                    models.FileField(
                        max_length=64,
                        upload_to=apps.news.models.upload_to_news,
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "short_text",
                    models.CharField(max_length=255, verbose_name="Краткое описание"),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        max_length=10000, verbose_name="Текст новости"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новости",
                "verbose_name_plural": "Новости",
                "ordering": ("-created",),
            },
        ),
    ]
